"""Razer standard 90-byte USB HID transaction protocol implementation.

References:
- openrazer/openrazer driver/razercommon.h & driver/razercommon.c
- scripts/wireshark/razer.lua
"""

from __future__ import annotations

import struct
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

from rzropenaud_io.constants import (
    CMD_ID_GET_EQUALIZER,
    CMD_ID_GET_FIRMWARE_VERSION,
    CMD_ID_GET_MIC_BOOST,
    CMD_ID_GET_MIC_VOLUME,
    CMD_ID_GET_SERIAL_NUMBER,
    CMD_ID_GET_SIDETONE,
    CMD_ID_SET_BASS_BOOST,
    CMD_ID_SET_EQUALIZER,
    CMD_ID_SET_MIC_BOOST,
    CMD_ID_SET_MIC_VOLUME,
    CMD_ID_SET_SIDETONE,
    CMD_ID_SET_VOICE_CLARITY,
    COMMAND_CLASS_AUDIO,
    COMMAND_CLASS_SYSTEM,
    DEFAULT_TRANSACTION_ID,
    RAZER_ARGUMENT_LEN,
    RAZER_CMD_NEW,
    RAZER_CMD_SUCCESSFUL,
    RAZER_REPORT_LEN,
    STATUS_NAMES,
)


def calculate_razer_crc(report: bytes | bytearray) -> int:
    """Calculate the XOR checksum for a 90-byte Razer report.

    As defined in OpenRazer (razer_calculate_crc):
    The checksum is generated by XORing all bytes in the report starting
    at index 2 and ending at index 87 (i < 88).
    Byte 88 holds this calculated CRC, and byte 89 is reserved (0x00).
    """
    if len(report) < 88:
        raise ValueError(f"Report buffer too short to compute CRC: {len(report)} bytes")

    crc = 0
    for b in report[2:88]:
        crc ^= b
    return crc


@dataclass
class RazerReport:
    """Represents a 90-byte standard Razer USB HID transaction report."""

    status: int = RAZER_CMD_NEW
    transaction_id: int = DEFAULT_TRANSACTION_ID
    remaining_packets: int = 0
    protocol_type: int = 0
    data_size: int = 0
    command_class: int = 0
    command_id: int = 0
    arguments: bytearray = field(default_factory=lambda: bytearray(RAZER_ARGUMENT_LEN))
    crc: int = 0
    reserved: int = 0

    def pack(self) -> bytes:
        """Serialize the report into the standard 90-byte binary payload."""
        buf = bytearray(RAZER_REPORT_LEN)

        # Byte 0: Status
        buf[0] = self.status & 0xFF
        # Byte 1: Transaction ID
        buf[1] = self.transaction_id & 0xFF
        # Bytes 2-3: Remaining Packets (Big-Endian uint16)
        struct.pack_into(">H", buf, 2, self.remaining_packets & 0xFFFF)
        # Byte 4: Protocol Type (0x00)
        buf[4] = self.protocol_type & 0xFF
        # Byte 5: Data Size (number of parameter bytes)
        buf[5] = self.data_size & 0xFF
        # Byte 6: Command Class
        buf[6] = self.command_class & 0xFF
        # Byte 7: Command ID
        buf[7] = self.command_id & 0xFF

        # Bytes 8-87: Arguments (80 bytes)
        arg_len = min(len(self.arguments), RAZER_ARGUMENT_LEN)
        buf[8 : 8 + arg_len] = self.arguments[:arg_len]
        # Pad remaining args with 0x00
        for i in range(8 + arg_len, 88):
            buf[i] = 0x00

        # Byte 88: XOR Checksum of bytes 2..87
        self.crc = calculate_razer_crc(buf)
        buf[88] = self.crc & 0xFF

        # Byte 89: Reserved (0x00)
        buf[89] = 0x00

        return bytes(buf)

    @classmethod
    def unpack(cls, raw: bytes | bytearray) -> RazerReport:
        """Deserialize a 90-byte (or 91-byte with report ID) buffer into a RazerReport."""
        # If payload is 91 bytes, strip leading report ID
        if len(raw) == 91:
            raw = raw[1:]

        if len(raw) != RAZER_REPORT_LEN:
            raise ValueError(
                f"Invalid Razer report length: {len(raw)} bytes (expected {RAZER_REPORT_LEN})"
            )

        status = raw[0]
        tx_id = raw[1]
        rem_packets = struct.unpack_from(">H", raw, 2)[0]
        proto = raw[4]
        data_size = raw[5]
        cmd_class = raw[6]
        cmd_id = raw[7]
        arguments = bytearray(raw[8:88])
        crc = raw[88]
        reserved = raw[89]

        calc_crc = calculate_razer_crc(raw)
        if crc != calc_crc:
            # We don't raise an exception immediately to allow parsing corrupted packets,
            # but callers can verify crc == calc_crc.
            pass

        return cls(
            status=status,
            transaction_id=tx_id,
            remaining_packets=rem_packets,
            protocol_type=proto,
            data_size=data_size,
            command_class=cmd_class,
            command_id=cmd_id,
            arguments=arguments,
            crc=crc,
            reserved=reserved,
        )

    def is_successful(self) -> bool:
        """Check whether the acknowledgement status indicates success."""
        return self.status == RAZER_CMD_SUCCESSFUL

    def status_string(self) -> str:
        """Get human-readable status description."""
        return STATUS_NAMES.get(self.status, f"Unknown status (0x{self.status:02X})")


def build_razer_report(
    command_class: int,
    command_id: int,
    args: bytes | bytearray | List[int] = b"",
    transaction_id: int = DEFAULT_TRANSACTION_ID,
) -> bytes:
    """Convenience factory function to build a 90-byte Razer report payload."""
    arg_bytes = bytearray(args)
    report = RazerReport(
        status=RAZER_CMD_NEW,
        transaction_id=transaction_id,
        remaining_packets=0,
        protocol_type=0,
        data_size=len(arg_bytes),
        command_class=command_class,
        command_id=command_id,
        arguments=arg_bytes,
    )
    return report.pack()


# -------------------------------------------------------------------------
# High-Level Audio & System Command Helpers
# -------------------------------------------------------------------------

def make_mic_volume_report(volume: int) -> bytes:
    """Create command to set microphone volume (0-100%)."""
    clamped = max(0, min(100, volume))
    # Arguments: [volume]
    return build_razer_report(
        command_class=COMMAND_CLASS_AUDIO,
        command_id=CMD_ID_SET_MIC_VOLUME,
        args=[clamped],
    )


def make_get_mic_volume_report() -> bytes:
    """Create command to query current microphone volume."""
    return build_razer_report(
        command_class=COMMAND_CLASS_AUDIO,
        command_id=CMD_ID_GET_MIC_VOLUME,
        args=[0x00],
    )


def make_sidetone_report(volume: int, enabled: Optional[bool] = None) -> bytes:
    """Create command to set sidetone (mic monitoring) level (0-100%) and enable toggle."""
    clamped = max(0, min(100, volume))
    is_on = (clamped > 0) if enabled is None else enabled
    # Arguments: [enabled (0x01/0x00), volume (0-100)]
    return build_razer_report(
        command_class=COMMAND_CLASS_AUDIO,
        command_id=CMD_ID_SET_SIDETONE,
        args=[0x01 if is_on else 0x00, clamped],
    )


def make_get_sidetone_report() -> bytes:
    """Create command to query current sidetone level."""
    return build_razer_report(
        command_class=COMMAND_CLASS_AUDIO,
        command_id=CMD_ID_GET_SIDETONE,
        args=[0x00],
    )


def make_equalizer_report(preset_idx: int, bands: List[int]) -> bytes:
    """Create command to set 10-band equalizer settings.

    bands: list of 10 integer gain values (typically -12 to +12 dB).
    """
    clamped_bands = [max(-12, min(12, int(b))) for b in bands[:10]]
    while len(clamped_bands) < 10:
        clamped_bands.append(0)

    # Encode gains: signed 8-bit integers (& 0xFF)
    encoded = [b & 0xFF for b in clamped_bands]
    # Arguments: [preset_id, band0, band1, ..., band9]
    return build_razer_report(
        command_class=COMMAND_CLASS_AUDIO,
        command_id=CMD_ID_SET_EQUALIZER,
        args=[preset_idx & 0xFF] + encoded,
    )


def make_get_equalizer_report() -> bytes:
    """Create command to query current equalizer configuration."""
    return build_razer_report(
        command_class=COMMAND_CLASS_AUDIO,
        command_id=CMD_ID_GET_EQUALIZER,
        args=[0x00],
    )


def make_mic_boost_report(enabled: bool) -> bytes:
    """Create command to set mic boost on or off."""
    return build_razer_report(
        command_class=COMMAND_CLASS_AUDIO,
        command_id=CMD_ID_SET_MIC_BOOST,
        args=[0x01 if enabled else 0x00],
    )


def make_bass_boost_report(level: int) -> bytes:
    """Create command to set bass boost level (0-100%)."""
    clamped = max(0, min(100, level))
    return build_razer_report(
        command_class=COMMAND_CLASS_AUDIO,
        command_id=CMD_ID_SET_BASS_BOOST,
        args=[clamped],
    )


def make_voice_clarity_report(level: int) -> bytes:
    """Create command to set voice clarity / ambient noise reduction (0-100%)."""
    clamped = max(0, min(100, level))
    return build_razer_report(
        command_class=COMMAND_CLASS_AUDIO,
        command_id=CMD_ID_SET_VOICE_CLARITY,
        args=[clamped],
    )


def make_get_firmware_version_report() -> bytes:
    """Create command to get device firmware version."""
    return build_razer_report(
        command_class=COMMAND_CLASS_SYSTEM,
        command_id=CMD_ID_GET_FIRMWARE_VERSION,
        args=[0x00],
    )


def make_get_serial_number_report() -> bytes:
    """Create command to get device serial number."""
    return build_razer_report(
        command_class=COMMAND_CLASS_SYSTEM,
        command_id=CMD_ID_GET_SERIAL_NUMBER,
        args=[0x00],
    )
